// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.router.admin.proto

package info.malenkov.aspiabot.proto;

public interface AdminToRouterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiabot.proto.AdminToRouter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.info.malenkov.aspiabot.proto.SessionListRequest session_list_request = 1;</code>
   * @return Whether the sessionListRequest field is set.
   */
  boolean hasSessionListRequest();
  /**
   * <code>.info.malenkov.aspiabot.proto.SessionListRequest session_list_request = 1;</code>
   * @return The sessionListRequest.
   */
  info.malenkov.aspiabot.proto.SessionListRequest getSessionListRequest();
  /**
   * <code>.info.malenkov.aspiabot.proto.SessionListRequest session_list_request = 1;</code>
   */
  info.malenkov.aspiabot.proto.SessionListRequestOrBuilder getSessionListRequestOrBuilder();

  /**
   * <code>.info.malenkov.aspiabot.proto.SessionRequest session_request = 2;</code>
   * @return Whether the sessionRequest field is set.
   */
  boolean hasSessionRequest();
  /**
   * <code>.info.malenkov.aspiabot.proto.SessionRequest session_request = 2;</code>
   * @return The sessionRequest.
   */
  info.malenkov.aspiabot.proto.SessionRequest getSessionRequest();
  /**
   * <code>.info.malenkov.aspiabot.proto.SessionRequest session_request = 2;</code>
   */
  info.malenkov.aspiabot.proto.SessionRequestOrBuilder getSessionRequestOrBuilder();

  /**
   * <code>.info.malenkov.aspiabot.proto.UserListRequest user_list_request = 3;</code>
   * @return Whether the userListRequest field is set.
   */
  boolean hasUserListRequest();
  /**
   * <code>.info.malenkov.aspiabot.proto.UserListRequest user_list_request = 3;</code>
   * @return The userListRequest.
   */
  info.malenkov.aspiabot.proto.UserListRequest getUserListRequest();
  /**
   * <code>.info.malenkov.aspiabot.proto.UserListRequest user_list_request = 3;</code>
   */
  info.malenkov.aspiabot.proto.UserListRequestOrBuilder getUserListRequestOrBuilder();

  /**
   * <code>.info.malenkov.aspiabot.proto.UserRequest user_request = 4;</code>
   * @return Whether the userRequest field is set.
   */
  boolean hasUserRequest();
  /**
   * <code>.info.malenkov.aspiabot.proto.UserRequest user_request = 4;</code>
   * @return The userRequest.
   */
  info.malenkov.aspiabot.proto.UserRequest getUserRequest();
  /**
   * <code>.info.malenkov.aspiabot.proto.UserRequest user_request = 4;</code>
   */
  info.malenkov.aspiabot.proto.UserRequestOrBuilder getUserRequestOrBuilder();
}
