// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.key.exchange.proto

package info.malenkov.aspiabot.proto;

/**
 * <pre>
 * Client to server.
 * </pre>
 *
 * Protobuf type {@code info.malenkov.aspiabot.proto.ClientHello}
 */
public final class ClientHello extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:info.malenkov.aspiabot.proto.ClientHello)
    ClientHelloOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientHello.newBuilder() to construct.
  private ClientHello(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientHello() {
    identify_ = 0;
    publicKey_ = com.google.protobuf.ByteString.EMPTY;
    iv_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ClientHello();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientHello(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            encryption_ = input.readUInt32();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            identify_ = rawValue;
            break;
          }
          case 26: {

            publicKey_ = input.readBytes();
            break;
          }
          case 34: {

            iv_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return info.malenkov.aspiabot.proto.AspiaKeyExchange.internal_static_info_malenkov_aspiabot_proto_ClientHello_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return info.malenkov.aspiabot.proto.AspiaKeyExchange.internal_static_info_malenkov_aspiabot_proto_ClientHello_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            info.malenkov.aspiabot.proto.ClientHello.class, info.malenkov.aspiabot.proto.ClientHello.Builder.class);
  }

  public static final int ENCRYPTION_FIELD_NUMBER = 1;
  private int encryption_;
  /**
   * <code>uint32 encryption = 1;</code>
   * @return The encryption.
   */
  @java.lang.Override
  public int getEncryption() {
    return encryption_;
  }

  public static final int IDENTIFY_FIELD_NUMBER = 2;
  private int identify_;
  /**
   * <code>.info.malenkov.aspiabot.proto.Identify identify = 2;</code>
   * @return The enum numeric value on the wire for identify.
   */
  @java.lang.Override public int getIdentifyValue() {
    return identify_;
  }
  /**
   * <code>.info.malenkov.aspiabot.proto.Identify identify = 2;</code>
   * @return The identify.
   */
  @java.lang.Override public info.malenkov.aspiabot.proto.Identify getIdentify() {
    @SuppressWarnings("deprecation")
    info.malenkov.aspiabot.proto.Identify result = info.malenkov.aspiabot.proto.Identify.valueOf(identify_);
    return result == null ? info.malenkov.aspiabot.proto.Identify.UNRECOGNIZED : result;
  }

  public static final int PUBLIC_KEY_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString publicKey_;
  /**
   * <code>bytes public_key = 3;</code>
   * @return The publicKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPublicKey() {
    return publicKey_;
  }

  public static final int IV_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString iv_;
  /**
   * <code>bytes iv = 4;</code>
   * @return The iv.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getIv() {
    return iv_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (encryption_ != 0) {
      output.writeUInt32(1, encryption_);
    }
    if (identify_ != info.malenkov.aspiabot.proto.Identify.IDENTIFY_SRP.getNumber()) {
      output.writeEnum(2, identify_);
    }
    if (!publicKey_.isEmpty()) {
      output.writeBytes(3, publicKey_);
    }
    if (!iv_.isEmpty()) {
      output.writeBytes(4, iv_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (encryption_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, encryption_);
    }
    if (identify_ != info.malenkov.aspiabot.proto.Identify.IDENTIFY_SRP.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, identify_);
    }
    if (!publicKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, publicKey_);
    }
    if (!iv_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, iv_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof info.malenkov.aspiabot.proto.ClientHello)) {
      return super.equals(obj);
    }
    info.malenkov.aspiabot.proto.ClientHello other = (info.malenkov.aspiabot.proto.ClientHello) obj;

    if (getEncryption()
        != other.getEncryption()) return false;
    if (identify_ != other.identify_) return false;
    if (!getPublicKey()
        .equals(other.getPublicKey())) return false;
    if (!getIv()
        .equals(other.getIv())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENCRYPTION_FIELD_NUMBER;
    hash = (53 * hash) + getEncryption();
    hash = (37 * hash) + IDENTIFY_FIELD_NUMBER;
    hash = (53 * hash) + identify_;
    hash = (37 * hash) + PUBLIC_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getPublicKey().hashCode();
    hash = (37 * hash) + IV_FIELD_NUMBER;
    hash = (53 * hash) + getIv().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static info.malenkov.aspiabot.proto.ClientHello parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabot.proto.ClientHello parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.ClientHello parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabot.proto.ClientHello parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.ClientHello parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabot.proto.ClientHello parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.ClientHello parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabot.proto.ClientHello parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.ClientHello parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabot.proto.ClientHello parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.ClientHello parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabot.proto.ClientHello parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(info.malenkov.aspiabot.proto.ClientHello prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Client to server.
   * </pre>
   *
   * Protobuf type {@code info.malenkov.aspiabot.proto.ClientHello}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:info.malenkov.aspiabot.proto.ClientHello)
      info.malenkov.aspiabot.proto.ClientHelloOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.malenkov.aspiabot.proto.AspiaKeyExchange.internal_static_info_malenkov_aspiabot_proto_ClientHello_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.malenkov.aspiabot.proto.AspiaKeyExchange.internal_static_info_malenkov_aspiabot_proto_ClientHello_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.malenkov.aspiabot.proto.ClientHello.class, info.malenkov.aspiabot.proto.ClientHello.Builder.class);
    }

    // Construct using info.malenkov.aspiabot.proto.ClientHello.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      encryption_ = 0;

      identify_ = 0;

      publicKey_ = com.google.protobuf.ByteString.EMPTY;

      iv_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return info.malenkov.aspiabot.proto.AspiaKeyExchange.internal_static_info_malenkov_aspiabot_proto_ClientHello_descriptor;
    }

    @java.lang.Override
    public info.malenkov.aspiabot.proto.ClientHello getDefaultInstanceForType() {
      return info.malenkov.aspiabot.proto.ClientHello.getDefaultInstance();
    }

    @java.lang.Override
    public info.malenkov.aspiabot.proto.ClientHello build() {
      info.malenkov.aspiabot.proto.ClientHello result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public info.malenkov.aspiabot.proto.ClientHello buildPartial() {
      info.malenkov.aspiabot.proto.ClientHello result = new info.malenkov.aspiabot.proto.ClientHello(this);
      result.encryption_ = encryption_;
      result.identify_ = identify_;
      result.publicKey_ = publicKey_;
      result.iv_ = iv_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof info.malenkov.aspiabot.proto.ClientHello) {
        return mergeFrom((info.malenkov.aspiabot.proto.ClientHello)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(info.malenkov.aspiabot.proto.ClientHello other) {
      if (other == info.malenkov.aspiabot.proto.ClientHello.getDefaultInstance()) return this;
      if (other.getEncryption() != 0) {
        setEncryption(other.getEncryption());
      }
      if (other.identify_ != 0) {
        setIdentifyValue(other.getIdentifyValue());
      }
      if (other.getPublicKey() != com.google.protobuf.ByteString.EMPTY) {
        setPublicKey(other.getPublicKey());
      }
      if (other.getIv() != com.google.protobuf.ByteString.EMPTY) {
        setIv(other.getIv());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      info.malenkov.aspiabot.proto.ClientHello parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (info.malenkov.aspiabot.proto.ClientHello) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int encryption_ ;
    /**
     * <code>uint32 encryption = 1;</code>
     * @return The encryption.
     */
    @java.lang.Override
    public int getEncryption() {
      return encryption_;
    }
    /**
     * <code>uint32 encryption = 1;</code>
     * @param value The encryption to set.
     * @return This builder for chaining.
     */
    public Builder setEncryption(int value) {
      
      encryption_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 encryption = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncryption() {
      
      encryption_ = 0;
      onChanged();
      return this;
    }

    private int identify_ = 0;
    /**
     * <code>.info.malenkov.aspiabot.proto.Identify identify = 2;</code>
     * @return The enum numeric value on the wire for identify.
     */
    @java.lang.Override public int getIdentifyValue() {
      return identify_;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.Identify identify = 2;</code>
     * @param value The enum numeric value on the wire for identify to set.
     * @return This builder for chaining.
     */
    public Builder setIdentifyValue(int value) {
      
      identify_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.Identify identify = 2;</code>
     * @return The identify.
     */
    @java.lang.Override
    public info.malenkov.aspiabot.proto.Identify getIdentify() {
      @SuppressWarnings("deprecation")
      info.malenkov.aspiabot.proto.Identify result = info.malenkov.aspiabot.proto.Identify.valueOf(identify_);
      return result == null ? info.malenkov.aspiabot.proto.Identify.UNRECOGNIZED : result;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.Identify identify = 2;</code>
     * @param value The identify to set.
     * @return This builder for chaining.
     */
    public Builder setIdentify(info.malenkov.aspiabot.proto.Identify value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      identify_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.Identify identify = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdentify() {
      
      identify_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes public_key = 3;</code>
     * @return The publicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }
    /**
     * <code>bytes public_key = 3;</code>
     * @param value The publicKey to set.
     * @return This builder for chaining.
     */
    public Builder setPublicKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      publicKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes public_key = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublicKey() {
      
      publicKey_ = getDefaultInstance().getPublicKey();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString iv_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes iv = 4;</code>
     * @return The iv.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIv() {
      return iv_;
    }
    /**
     * <code>bytes iv = 4;</code>
     * @param value The iv to set.
     * @return This builder for chaining.
     */
    public Builder setIv(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      iv_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes iv = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIv() {
      
      iv_ = getDefaultInstance().getIv();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:info.malenkov.aspiabot.proto.ClientHello)
  }

  // @@protoc_insertion_point(class_scope:info.malenkov.aspiabot.proto.ClientHello)
  private static final info.malenkov.aspiabot.proto.ClientHello DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new info.malenkov.aspiabot.proto.ClientHello();
  }

  public static info.malenkov.aspiabot.proto.ClientHello getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientHello>
      PARSER = new com.google.protobuf.AbstractParser<ClientHello>() {
    @java.lang.Override
    public ClientHello parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientHello(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientHello> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientHello> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public info.malenkov.aspiabot.proto.ClientHello getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

