// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.router.admin.proto

package info.malenkov.aspiabot.proto;

public interface RelaySessionDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiabot.proto.RelaySessionData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 pool_size = 1;</code>
   * @return The poolSize.
   */
  long getPoolSize();
}
