// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.router.admin.proto

package info.malenkov.aspiabot.proto;

/**
 * Protobuf type {@code info.malenkov.aspiabot.proto.RouterToAdmin}
 */
public final class RouterToAdmin extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:info.malenkov.aspiabot.proto.RouterToAdmin)
    RouterToAdminOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RouterToAdmin.newBuilder() to construct.
  private RouterToAdmin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RouterToAdmin() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RouterToAdmin();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RouterToAdmin(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            info.malenkov.aspiabot.proto.SessionList.Builder subBuilder = null;
            if (sessionList_ != null) {
              subBuilder = sessionList_.toBuilder();
            }
            sessionList_ = input.readMessage(info.malenkov.aspiabot.proto.SessionList.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(sessionList_);
              sessionList_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            info.malenkov.aspiabot.proto.SessionResult.Builder subBuilder = null;
            if (sessionResult_ != null) {
              subBuilder = sessionResult_.toBuilder();
            }
            sessionResult_ = input.readMessage(info.malenkov.aspiabot.proto.SessionResult.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(sessionResult_);
              sessionResult_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            info.malenkov.aspiabot.proto.UserList.Builder subBuilder = null;
            if (userList_ != null) {
              subBuilder = userList_.toBuilder();
            }
            userList_ = input.readMessage(info.malenkov.aspiabot.proto.UserList.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(userList_);
              userList_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            info.malenkov.aspiabot.proto.UserResult.Builder subBuilder = null;
            if (userResult_ != null) {
              subBuilder = userResult_.toBuilder();
            }
            userResult_ = input.readMessage(info.malenkov.aspiabot.proto.UserResult.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(userResult_);
              userResult_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return info.malenkov.aspiabot.proto.AspiaRouterAdmin.internal_static_info_malenkov_aspiabot_proto_RouterToAdmin_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return info.malenkov.aspiabot.proto.AspiaRouterAdmin.internal_static_info_malenkov_aspiabot_proto_RouterToAdmin_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            info.malenkov.aspiabot.proto.RouterToAdmin.class, info.malenkov.aspiabot.proto.RouterToAdmin.Builder.class);
  }

  public static final int SESSION_LIST_FIELD_NUMBER = 1;
  private info.malenkov.aspiabot.proto.SessionList sessionList_;
  /**
   * <code>.info.malenkov.aspiabot.proto.SessionList session_list = 1;</code>
   * @return Whether the sessionList field is set.
   */
  @java.lang.Override
  public boolean hasSessionList() {
    return sessionList_ != null;
  }
  /**
   * <code>.info.malenkov.aspiabot.proto.SessionList session_list = 1;</code>
   * @return The sessionList.
   */
  @java.lang.Override
  public info.malenkov.aspiabot.proto.SessionList getSessionList() {
    return sessionList_ == null ? info.malenkov.aspiabot.proto.SessionList.getDefaultInstance() : sessionList_;
  }
  /**
   * <code>.info.malenkov.aspiabot.proto.SessionList session_list = 1;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiabot.proto.SessionListOrBuilder getSessionListOrBuilder() {
    return getSessionList();
  }

  public static final int SESSION_RESULT_FIELD_NUMBER = 2;
  private info.malenkov.aspiabot.proto.SessionResult sessionResult_;
  /**
   * <code>.info.malenkov.aspiabot.proto.SessionResult session_result = 2;</code>
   * @return Whether the sessionResult field is set.
   */
  @java.lang.Override
  public boolean hasSessionResult() {
    return sessionResult_ != null;
  }
  /**
   * <code>.info.malenkov.aspiabot.proto.SessionResult session_result = 2;</code>
   * @return The sessionResult.
   */
  @java.lang.Override
  public info.malenkov.aspiabot.proto.SessionResult getSessionResult() {
    return sessionResult_ == null ? info.malenkov.aspiabot.proto.SessionResult.getDefaultInstance() : sessionResult_;
  }
  /**
   * <code>.info.malenkov.aspiabot.proto.SessionResult session_result = 2;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiabot.proto.SessionResultOrBuilder getSessionResultOrBuilder() {
    return getSessionResult();
  }

  public static final int USER_LIST_FIELD_NUMBER = 3;
  private info.malenkov.aspiabot.proto.UserList userList_;
  /**
   * <code>.info.malenkov.aspiabot.proto.UserList user_list = 3;</code>
   * @return Whether the userList field is set.
   */
  @java.lang.Override
  public boolean hasUserList() {
    return userList_ != null;
  }
  /**
   * <code>.info.malenkov.aspiabot.proto.UserList user_list = 3;</code>
   * @return The userList.
   */
  @java.lang.Override
  public info.malenkov.aspiabot.proto.UserList getUserList() {
    return userList_ == null ? info.malenkov.aspiabot.proto.UserList.getDefaultInstance() : userList_;
  }
  /**
   * <code>.info.malenkov.aspiabot.proto.UserList user_list = 3;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiabot.proto.UserListOrBuilder getUserListOrBuilder() {
    return getUserList();
  }

  public static final int USER_RESULT_FIELD_NUMBER = 4;
  private info.malenkov.aspiabot.proto.UserResult userResult_;
  /**
   * <code>.info.malenkov.aspiabot.proto.UserResult user_result = 4;</code>
   * @return Whether the userResult field is set.
   */
  @java.lang.Override
  public boolean hasUserResult() {
    return userResult_ != null;
  }
  /**
   * <code>.info.malenkov.aspiabot.proto.UserResult user_result = 4;</code>
   * @return The userResult.
   */
  @java.lang.Override
  public info.malenkov.aspiabot.proto.UserResult getUserResult() {
    return userResult_ == null ? info.malenkov.aspiabot.proto.UserResult.getDefaultInstance() : userResult_;
  }
  /**
   * <code>.info.malenkov.aspiabot.proto.UserResult user_result = 4;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiabot.proto.UserResultOrBuilder getUserResultOrBuilder() {
    return getUserResult();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sessionList_ != null) {
      output.writeMessage(1, getSessionList());
    }
    if (sessionResult_ != null) {
      output.writeMessage(2, getSessionResult());
    }
    if (userList_ != null) {
      output.writeMessage(3, getUserList());
    }
    if (userResult_ != null) {
      output.writeMessage(4, getUserResult());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sessionList_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSessionList());
    }
    if (sessionResult_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getSessionResult());
    }
    if (userList_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getUserList());
    }
    if (userResult_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getUserResult());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof info.malenkov.aspiabot.proto.RouterToAdmin)) {
      return super.equals(obj);
    }
    info.malenkov.aspiabot.proto.RouterToAdmin other = (info.malenkov.aspiabot.proto.RouterToAdmin) obj;

    if (hasSessionList() != other.hasSessionList()) return false;
    if (hasSessionList()) {
      if (!getSessionList()
          .equals(other.getSessionList())) return false;
    }
    if (hasSessionResult() != other.hasSessionResult()) return false;
    if (hasSessionResult()) {
      if (!getSessionResult()
          .equals(other.getSessionResult())) return false;
    }
    if (hasUserList() != other.hasUserList()) return false;
    if (hasUserList()) {
      if (!getUserList()
          .equals(other.getUserList())) return false;
    }
    if (hasUserResult() != other.hasUserResult()) return false;
    if (hasUserResult()) {
      if (!getUserResult()
          .equals(other.getUserResult())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSessionList()) {
      hash = (37 * hash) + SESSION_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getSessionList().hashCode();
    }
    if (hasSessionResult()) {
      hash = (37 * hash) + SESSION_RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getSessionResult().hashCode();
    }
    if (hasUserList()) {
      hash = (37 * hash) + USER_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getUserList().hashCode();
    }
    if (hasUserResult()) {
      hash = (37 * hash) + USER_RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getUserResult().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static info.malenkov.aspiabot.proto.RouterToAdmin parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabot.proto.RouterToAdmin parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.RouterToAdmin parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabot.proto.RouterToAdmin parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.RouterToAdmin parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabot.proto.RouterToAdmin parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.RouterToAdmin parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabot.proto.RouterToAdmin parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.RouterToAdmin parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabot.proto.RouterToAdmin parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.RouterToAdmin parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabot.proto.RouterToAdmin parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(info.malenkov.aspiabot.proto.RouterToAdmin prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code info.malenkov.aspiabot.proto.RouterToAdmin}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:info.malenkov.aspiabot.proto.RouterToAdmin)
      info.malenkov.aspiabot.proto.RouterToAdminOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.malenkov.aspiabot.proto.AspiaRouterAdmin.internal_static_info_malenkov_aspiabot_proto_RouterToAdmin_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.malenkov.aspiabot.proto.AspiaRouterAdmin.internal_static_info_malenkov_aspiabot_proto_RouterToAdmin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.malenkov.aspiabot.proto.RouterToAdmin.class, info.malenkov.aspiabot.proto.RouterToAdmin.Builder.class);
    }

    // Construct using info.malenkov.aspiabot.proto.RouterToAdmin.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (sessionListBuilder_ == null) {
        sessionList_ = null;
      } else {
        sessionList_ = null;
        sessionListBuilder_ = null;
      }
      if (sessionResultBuilder_ == null) {
        sessionResult_ = null;
      } else {
        sessionResult_ = null;
        sessionResultBuilder_ = null;
      }
      if (userListBuilder_ == null) {
        userList_ = null;
      } else {
        userList_ = null;
        userListBuilder_ = null;
      }
      if (userResultBuilder_ == null) {
        userResult_ = null;
      } else {
        userResult_ = null;
        userResultBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return info.malenkov.aspiabot.proto.AspiaRouterAdmin.internal_static_info_malenkov_aspiabot_proto_RouterToAdmin_descriptor;
    }

    @java.lang.Override
    public info.malenkov.aspiabot.proto.RouterToAdmin getDefaultInstanceForType() {
      return info.malenkov.aspiabot.proto.RouterToAdmin.getDefaultInstance();
    }

    @java.lang.Override
    public info.malenkov.aspiabot.proto.RouterToAdmin build() {
      info.malenkov.aspiabot.proto.RouterToAdmin result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public info.malenkov.aspiabot.proto.RouterToAdmin buildPartial() {
      info.malenkov.aspiabot.proto.RouterToAdmin result = new info.malenkov.aspiabot.proto.RouterToAdmin(this);
      if (sessionListBuilder_ == null) {
        result.sessionList_ = sessionList_;
      } else {
        result.sessionList_ = sessionListBuilder_.build();
      }
      if (sessionResultBuilder_ == null) {
        result.sessionResult_ = sessionResult_;
      } else {
        result.sessionResult_ = sessionResultBuilder_.build();
      }
      if (userListBuilder_ == null) {
        result.userList_ = userList_;
      } else {
        result.userList_ = userListBuilder_.build();
      }
      if (userResultBuilder_ == null) {
        result.userResult_ = userResult_;
      } else {
        result.userResult_ = userResultBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof info.malenkov.aspiabot.proto.RouterToAdmin) {
        return mergeFrom((info.malenkov.aspiabot.proto.RouterToAdmin)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(info.malenkov.aspiabot.proto.RouterToAdmin other) {
      if (other == info.malenkov.aspiabot.proto.RouterToAdmin.getDefaultInstance()) return this;
      if (other.hasSessionList()) {
        mergeSessionList(other.getSessionList());
      }
      if (other.hasSessionResult()) {
        mergeSessionResult(other.getSessionResult());
      }
      if (other.hasUserList()) {
        mergeUserList(other.getUserList());
      }
      if (other.hasUserResult()) {
        mergeUserResult(other.getUserResult());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      info.malenkov.aspiabot.proto.RouterToAdmin parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (info.malenkov.aspiabot.proto.RouterToAdmin) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private info.malenkov.aspiabot.proto.SessionList sessionList_;
    private com.google.protobuf.SingleFieldBuilderV3<
        info.malenkov.aspiabot.proto.SessionList, info.malenkov.aspiabot.proto.SessionList.Builder, info.malenkov.aspiabot.proto.SessionListOrBuilder> sessionListBuilder_;
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionList session_list = 1;</code>
     * @return Whether the sessionList field is set.
     */
    public boolean hasSessionList() {
      return sessionListBuilder_ != null || sessionList_ != null;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionList session_list = 1;</code>
     * @return The sessionList.
     */
    public info.malenkov.aspiabot.proto.SessionList getSessionList() {
      if (sessionListBuilder_ == null) {
        return sessionList_ == null ? info.malenkov.aspiabot.proto.SessionList.getDefaultInstance() : sessionList_;
      } else {
        return sessionListBuilder_.getMessage();
      }
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionList session_list = 1;</code>
     */
    public Builder setSessionList(info.malenkov.aspiabot.proto.SessionList value) {
      if (sessionListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sessionList_ = value;
        onChanged();
      } else {
        sessionListBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionList session_list = 1;</code>
     */
    public Builder setSessionList(
        info.malenkov.aspiabot.proto.SessionList.Builder builderForValue) {
      if (sessionListBuilder_ == null) {
        sessionList_ = builderForValue.build();
        onChanged();
      } else {
        sessionListBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionList session_list = 1;</code>
     */
    public Builder mergeSessionList(info.malenkov.aspiabot.proto.SessionList value) {
      if (sessionListBuilder_ == null) {
        if (sessionList_ != null) {
          sessionList_ =
            info.malenkov.aspiabot.proto.SessionList.newBuilder(sessionList_).mergeFrom(value).buildPartial();
        } else {
          sessionList_ = value;
        }
        onChanged();
      } else {
        sessionListBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionList session_list = 1;</code>
     */
    public Builder clearSessionList() {
      if (sessionListBuilder_ == null) {
        sessionList_ = null;
        onChanged();
      } else {
        sessionList_ = null;
        sessionListBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionList session_list = 1;</code>
     */
    public info.malenkov.aspiabot.proto.SessionList.Builder getSessionListBuilder() {
      
      onChanged();
      return getSessionListFieldBuilder().getBuilder();
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionList session_list = 1;</code>
     */
    public info.malenkov.aspiabot.proto.SessionListOrBuilder getSessionListOrBuilder() {
      if (sessionListBuilder_ != null) {
        return sessionListBuilder_.getMessageOrBuilder();
      } else {
        return sessionList_ == null ?
            info.malenkov.aspiabot.proto.SessionList.getDefaultInstance() : sessionList_;
      }
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionList session_list = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        info.malenkov.aspiabot.proto.SessionList, info.malenkov.aspiabot.proto.SessionList.Builder, info.malenkov.aspiabot.proto.SessionListOrBuilder> 
        getSessionListFieldBuilder() {
      if (sessionListBuilder_ == null) {
        sessionListBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            info.malenkov.aspiabot.proto.SessionList, info.malenkov.aspiabot.proto.SessionList.Builder, info.malenkov.aspiabot.proto.SessionListOrBuilder>(
                getSessionList(),
                getParentForChildren(),
                isClean());
        sessionList_ = null;
      }
      return sessionListBuilder_;
    }

    private info.malenkov.aspiabot.proto.SessionResult sessionResult_;
    private com.google.protobuf.SingleFieldBuilderV3<
        info.malenkov.aspiabot.proto.SessionResult, info.malenkov.aspiabot.proto.SessionResult.Builder, info.malenkov.aspiabot.proto.SessionResultOrBuilder> sessionResultBuilder_;
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionResult session_result = 2;</code>
     * @return Whether the sessionResult field is set.
     */
    public boolean hasSessionResult() {
      return sessionResultBuilder_ != null || sessionResult_ != null;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionResult session_result = 2;</code>
     * @return The sessionResult.
     */
    public info.malenkov.aspiabot.proto.SessionResult getSessionResult() {
      if (sessionResultBuilder_ == null) {
        return sessionResult_ == null ? info.malenkov.aspiabot.proto.SessionResult.getDefaultInstance() : sessionResult_;
      } else {
        return sessionResultBuilder_.getMessage();
      }
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionResult session_result = 2;</code>
     */
    public Builder setSessionResult(info.malenkov.aspiabot.proto.SessionResult value) {
      if (sessionResultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sessionResult_ = value;
        onChanged();
      } else {
        sessionResultBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionResult session_result = 2;</code>
     */
    public Builder setSessionResult(
        info.malenkov.aspiabot.proto.SessionResult.Builder builderForValue) {
      if (sessionResultBuilder_ == null) {
        sessionResult_ = builderForValue.build();
        onChanged();
      } else {
        sessionResultBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionResult session_result = 2;</code>
     */
    public Builder mergeSessionResult(info.malenkov.aspiabot.proto.SessionResult value) {
      if (sessionResultBuilder_ == null) {
        if (sessionResult_ != null) {
          sessionResult_ =
            info.malenkov.aspiabot.proto.SessionResult.newBuilder(sessionResult_).mergeFrom(value).buildPartial();
        } else {
          sessionResult_ = value;
        }
        onChanged();
      } else {
        sessionResultBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionResult session_result = 2;</code>
     */
    public Builder clearSessionResult() {
      if (sessionResultBuilder_ == null) {
        sessionResult_ = null;
        onChanged();
      } else {
        sessionResult_ = null;
        sessionResultBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionResult session_result = 2;</code>
     */
    public info.malenkov.aspiabot.proto.SessionResult.Builder getSessionResultBuilder() {
      
      onChanged();
      return getSessionResultFieldBuilder().getBuilder();
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionResult session_result = 2;</code>
     */
    public info.malenkov.aspiabot.proto.SessionResultOrBuilder getSessionResultOrBuilder() {
      if (sessionResultBuilder_ != null) {
        return sessionResultBuilder_.getMessageOrBuilder();
      } else {
        return sessionResult_ == null ?
            info.malenkov.aspiabot.proto.SessionResult.getDefaultInstance() : sessionResult_;
      }
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionResult session_result = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        info.malenkov.aspiabot.proto.SessionResult, info.malenkov.aspiabot.proto.SessionResult.Builder, info.malenkov.aspiabot.proto.SessionResultOrBuilder> 
        getSessionResultFieldBuilder() {
      if (sessionResultBuilder_ == null) {
        sessionResultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            info.malenkov.aspiabot.proto.SessionResult, info.malenkov.aspiabot.proto.SessionResult.Builder, info.malenkov.aspiabot.proto.SessionResultOrBuilder>(
                getSessionResult(),
                getParentForChildren(),
                isClean());
        sessionResult_ = null;
      }
      return sessionResultBuilder_;
    }

    private info.malenkov.aspiabot.proto.UserList userList_;
    private com.google.protobuf.SingleFieldBuilderV3<
        info.malenkov.aspiabot.proto.UserList, info.malenkov.aspiabot.proto.UserList.Builder, info.malenkov.aspiabot.proto.UserListOrBuilder> userListBuilder_;
    /**
     * <code>.info.malenkov.aspiabot.proto.UserList user_list = 3;</code>
     * @return Whether the userList field is set.
     */
    public boolean hasUserList() {
      return userListBuilder_ != null || userList_ != null;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.UserList user_list = 3;</code>
     * @return The userList.
     */
    public info.malenkov.aspiabot.proto.UserList getUserList() {
      if (userListBuilder_ == null) {
        return userList_ == null ? info.malenkov.aspiabot.proto.UserList.getDefaultInstance() : userList_;
      } else {
        return userListBuilder_.getMessage();
      }
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.UserList user_list = 3;</code>
     */
    public Builder setUserList(info.malenkov.aspiabot.proto.UserList value) {
      if (userListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userList_ = value;
        onChanged();
      } else {
        userListBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.UserList user_list = 3;</code>
     */
    public Builder setUserList(
        info.malenkov.aspiabot.proto.UserList.Builder builderForValue) {
      if (userListBuilder_ == null) {
        userList_ = builderForValue.build();
        onChanged();
      } else {
        userListBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.UserList user_list = 3;</code>
     */
    public Builder mergeUserList(info.malenkov.aspiabot.proto.UserList value) {
      if (userListBuilder_ == null) {
        if (userList_ != null) {
          userList_ =
            info.malenkov.aspiabot.proto.UserList.newBuilder(userList_).mergeFrom(value).buildPartial();
        } else {
          userList_ = value;
        }
        onChanged();
      } else {
        userListBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.UserList user_list = 3;</code>
     */
    public Builder clearUserList() {
      if (userListBuilder_ == null) {
        userList_ = null;
        onChanged();
      } else {
        userList_ = null;
        userListBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.UserList user_list = 3;</code>
     */
    public info.malenkov.aspiabot.proto.UserList.Builder getUserListBuilder() {
      
      onChanged();
      return getUserListFieldBuilder().getBuilder();
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.UserList user_list = 3;</code>
     */
    public info.malenkov.aspiabot.proto.UserListOrBuilder getUserListOrBuilder() {
      if (userListBuilder_ != null) {
        return userListBuilder_.getMessageOrBuilder();
      } else {
        return userList_ == null ?
            info.malenkov.aspiabot.proto.UserList.getDefaultInstance() : userList_;
      }
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.UserList user_list = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        info.malenkov.aspiabot.proto.UserList, info.malenkov.aspiabot.proto.UserList.Builder, info.malenkov.aspiabot.proto.UserListOrBuilder> 
        getUserListFieldBuilder() {
      if (userListBuilder_ == null) {
        userListBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            info.malenkov.aspiabot.proto.UserList, info.malenkov.aspiabot.proto.UserList.Builder, info.malenkov.aspiabot.proto.UserListOrBuilder>(
                getUserList(),
                getParentForChildren(),
                isClean());
        userList_ = null;
      }
      return userListBuilder_;
    }

    private info.malenkov.aspiabot.proto.UserResult userResult_;
    private com.google.protobuf.SingleFieldBuilderV3<
        info.malenkov.aspiabot.proto.UserResult, info.malenkov.aspiabot.proto.UserResult.Builder, info.malenkov.aspiabot.proto.UserResultOrBuilder> userResultBuilder_;
    /**
     * <code>.info.malenkov.aspiabot.proto.UserResult user_result = 4;</code>
     * @return Whether the userResult field is set.
     */
    public boolean hasUserResult() {
      return userResultBuilder_ != null || userResult_ != null;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.UserResult user_result = 4;</code>
     * @return The userResult.
     */
    public info.malenkov.aspiabot.proto.UserResult getUserResult() {
      if (userResultBuilder_ == null) {
        return userResult_ == null ? info.malenkov.aspiabot.proto.UserResult.getDefaultInstance() : userResult_;
      } else {
        return userResultBuilder_.getMessage();
      }
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.UserResult user_result = 4;</code>
     */
    public Builder setUserResult(info.malenkov.aspiabot.proto.UserResult value) {
      if (userResultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userResult_ = value;
        onChanged();
      } else {
        userResultBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.UserResult user_result = 4;</code>
     */
    public Builder setUserResult(
        info.malenkov.aspiabot.proto.UserResult.Builder builderForValue) {
      if (userResultBuilder_ == null) {
        userResult_ = builderForValue.build();
        onChanged();
      } else {
        userResultBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.UserResult user_result = 4;</code>
     */
    public Builder mergeUserResult(info.malenkov.aspiabot.proto.UserResult value) {
      if (userResultBuilder_ == null) {
        if (userResult_ != null) {
          userResult_ =
            info.malenkov.aspiabot.proto.UserResult.newBuilder(userResult_).mergeFrom(value).buildPartial();
        } else {
          userResult_ = value;
        }
        onChanged();
      } else {
        userResultBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.UserResult user_result = 4;</code>
     */
    public Builder clearUserResult() {
      if (userResultBuilder_ == null) {
        userResult_ = null;
        onChanged();
      } else {
        userResult_ = null;
        userResultBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.UserResult user_result = 4;</code>
     */
    public info.malenkov.aspiabot.proto.UserResult.Builder getUserResultBuilder() {
      
      onChanged();
      return getUserResultFieldBuilder().getBuilder();
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.UserResult user_result = 4;</code>
     */
    public info.malenkov.aspiabot.proto.UserResultOrBuilder getUserResultOrBuilder() {
      if (userResultBuilder_ != null) {
        return userResultBuilder_.getMessageOrBuilder();
      } else {
        return userResult_ == null ?
            info.malenkov.aspiabot.proto.UserResult.getDefaultInstance() : userResult_;
      }
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.UserResult user_result = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        info.malenkov.aspiabot.proto.UserResult, info.malenkov.aspiabot.proto.UserResult.Builder, info.malenkov.aspiabot.proto.UserResultOrBuilder> 
        getUserResultFieldBuilder() {
      if (userResultBuilder_ == null) {
        userResultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            info.malenkov.aspiabot.proto.UserResult, info.malenkov.aspiabot.proto.UserResult.Builder, info.malenkov.aspiabot.proto.UserResultOrBuilder>(
                getUserResult(),
                getParentForChildren(),
                isClean());
        userResult_ = null;
      }
      return userResultBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:info.malenkov.aspiabot.proto.RouterToAdmin)
  }

  // @@protoc_insertion_point(class_scope:info.malenkov.aspiabot.proto.RouterToAdmin)
  private static final info.malenkov.aspiabot.proto.RouterToAdmin DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new info.malenkov.aspiabot.proto.RouterToAdmin();
  }

  public static info.malenkov.aspiabot.proto.RouterToAdmin getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RouterToAdmin>
      PARSER = new com.google.protobuf.AbstractParser<RouterToAdmin>() {
    @java.lang.Override
    public RouterToAdmin parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RouterToAdmin(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RouterToAdmin> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RouterToAdmin> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public info.malenkov.aspiabot.proto.RouterToAdmin getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

