// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.router.admin.proto

package info.malenkov.aspiabot.proto;

/**
 * Protobuf type {@code info.malenkov.aspiabot.proto.SessionList}
 */
public final class SessionList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:info.malenkov.aspiabot.proto.SessionList)
    SessionListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SessionList.newBuilder() to construct.
  private SessionList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SessionList() {
    errorCode_ = 0;
    session_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SessionList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SessionList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            errorCode_ = rawValue;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              session_ = new java.util.ArrayList<info.malenkov.aspiabot.proto.Session>();
              mutable_bitField0_ |= 0x00000001;
            }
            session_.add(
                input.readMessage(info.malenkov.aspiabot.proto.Session.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        session_ = java.util.Collections.unmodifiableList(session_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return info.malenkov.aspiabot.proto.AspiaRouterAdmin.internal_static_info_malenkov_aspiabot_proto_SessionList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return info.malenkov.aspiabot.proto.AspiaRouterAdmin.internal_static_info_malenkov_aspiabot_proto_SessionList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            info.malenkov.aspiabot.proto.SessionList.class, info.malenkov.aspiabot.proto.SessionList.Builder.class);
  }

  /**
   * Protobuf enum {@code info.malenkov.aspiabot.proto.SessionList.ErrorCode}
   */
  public enum ErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUCCESS = 0;</code>
     */
    SUCCESS(0),
    /**
     * <code>UNKNOWN_ERROR = 1;</code>
     */
    UNKNOWN_ERROR(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SUCCESS = 0;</code>
     */
    public static final int SUCCESS_VALUE = 0;
    /**
     * <code>UNKNOWN_ERROR = 1;</code>
     */
    public static final int UNKNOWN_ERROR_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ErrorCode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ErrorCode forNumber(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1: return UNKNOWN_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ErrorCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
            public ErrorCode findValueByNumber(int number) {
              return ErrorCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return info.malenkov.aspiabot.proto.SessionList.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrorCode[] VALUES = values();

    public static ErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ErrorCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:info.malenkov.aspiabot.proto.SessionList.ErrorCode)
  }

  public static final int ERROR_CODE_FIELD_NUMBER = 1;
  private int errorCode_;
  /**
   * <code>.info.malenkov.aspiabot.proto.SessionList.ErrorCode error_code = 1;</code>
   * @return The enum numeric value on the wire for errorCode.
   */
  @java.lang.Override public int getErrorCodeValue() {
    return errorCode_;
  }
  /**
   * <code>.info.malenkov.aspiabot.proto.SessionList.ErrorCode error_code = 1;</code>
   * @return The errorCode.
   */
  @java.lang.Override public info.malenkov.aspiabot.proto.SessionList.ErrorCode getErrorCode() {
    @SuppressWarnings("deprecation")
    info.malenkov.aspiabot.proto.SessionList.ErrorCode result = info.malenkov.aspiabot.proto.SessionList.ErrorCode.valueOf(errorCode_);
    return result == null ? info.malenkov.aspiabot.proto.SessionList.ErrorCode.UNRECOGNIZED : result;
  }

  public static final int SESSION_FIELD_NUMBER = 2;
  private java.util.List<info.malenkov.aspiabot.proto.Session> session_;
  /**
   * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
   */
  @java.lang.Override
  public java.util.List<info.malenkov.aspiabot.proto.Session> getSessionList() {
    return session_;
  }
  /**
   * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends info.malenkov.aspiabot.proto.SessionOrBuilder> 
      getSessionOrBuilderList() {
    return session_;
  }
  /**
   * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
   */
  @java.lang.Override
  public int getSessionCount() {
    return session_.size();
  }
  /**
   * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiabot.proto.Session getSession(int index) {
    return session_.get(index);
  }
  /**
   * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiabot.proto.SessionOrBuilder getSessionOrBuilder(
      int index) {
    return session_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (errorCode_ != info.malenkov.aspiabot.proto.SessionList.ErrorCode.SUCCESS.getNumber()) {
      output.writeEnum(1, errorCode_);
    }
    for (int i = 0; i < session_.size(); i++) {
      output.writeMessage(2, session_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (errorCode_ != info.malenkov.aspiabot.proto.SessionList.ErrorCode.SUCCESS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, errorCode_);
    }
    for (int i = 0; i < session_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, session_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof info.malenkov.aspiabot.proto.SessionList)) {
      return super.equals(obj);
    }
    info.malenkov.aspiabot.proto.SessionList other = (info.malenkov.aspiabot.proto.SessionList) obj;

    if (errorCode_ != other.errorCode_) return false;
    if (!getSessionList()
        .equals(other.getSessionList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ERROR_CODE_FIELD_NUMBER;
    hash = (53 * hash) + errorCode_;
    if (getSessionCount() > 0) {
      hash = (37 * hash) + SESSION_FIELD_NUMBER;
      hash = (53 * hash) + getSessionList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static info.malenkov.aspiabot.proto.SessionList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabot.proto.SessionList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.SessionList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabot.proto.SessionList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.SessionList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabot.proto.SessionList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.SessionList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabot.proto.SessionList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.SessionList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabot.proto.SessionList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.SessionList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabot.proto.SessionList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(info.malenkov.aspiabot.proto.SessionList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code info.malenkov.aspiabot.proto.SessionList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:info.malenkov.aspiabot.proto.SessionList)
      info.malenkov.aspiabot.proto.SessionListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.malenkov.aspiabot.proto.AspiaRouterAdmin.internal_static_info_malenkov_aspiabot_proto_SessionList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.malenkov.aspiabot.proto.AspiaRouterAdmin.internal_static_info_malenkov_aspiabot_proto_SessionList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.malenkov.aspiabot.proto.SessionList.class, info.malenkov.aspiabot.proto.SessionList.Builder.class);
    }

    // Construct using info.malenkov.aspiabot.proto.SessionList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSessionFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      errorCode_ = 0;

      if (sessionBuilder_ == null) {
        session_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        sessionBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return info.malenkov.aspiabot.proto.AspiaRouterAdmin.internal_static_info_malenkov_aspiabot_proto_SessionList_descriptor;
    }

    @java.lang.Override
    public info.malenkov.aspiabot.proto.SessionList getDefaultInstanceForType() {
      return info.malenkov.aspiabot.proto.SessionList.getDefaultInstance();
    }

    @java.lang.Override
    public info.malenkov.aspiabot.proto.SessionList build() {
      info.malenkov.aspiabot.proto.SessionList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public info.malenkov.aspiabot.proto.SessionList buildPartial() {
      info.malenkov.aspiabot.proto.SessionList result = new info.malenkov.aspiabot.proto.SessionList(this);
      int from_bitField0_ = bitField0_;
      result.errorCode_ = errorCode_;
      if (sessionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          session_ = java.util.Collections.unmodifiableList(session_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.session_ = session_;
      } else {
        result.session_ = sessionBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof info.malenkov.aspiabot.proto.SessionList) {
        return mergeFrom((info.malenkov.aspiabot.proto.SessionList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(info.malenkov.aspiabot.proto.SessionList other) {
      if (other == info.malenkov.aspiabot.proto.SessionList.getDefaultInstance()) return this;
      if (other.errorCode_ != 0) {
        setErrorCodeValue(other.getErrorCodeValue());
      }
      if (sessionBuilder_ == null) {
        if (!other.session_.isEmpty()) {
          if (session_.isEmpty()) {
            session_ = other.session_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSessionIsMutable();
            session_.addAll(other.session_);
          }
          onChanged();
        }
      } else {
        if (!other.session_.isEmpty()) {
          if (sessionBuilder_.isEmpty()) {
            sessionBuilder_.dispose();
            sessionBuilder_ = null;
            session_ = other.session_;
            bitField0_ = (bitField0_ & ~0x00000001);
            sessionBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSessionFieldBuilder() : null;
          } else {
            sessionBuilder_.addAllMessages(other.session_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      info.malenkov.aspiabot.proto.SessionList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (info.malenkov.aspiabot.proto.SessionList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int errorCode_ = 0;
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionList.ErrorCode error_code = 1;</code>
     * @return The enum numeric value on the wire for errorCode.
     */
    @java.lang.Override public int getErrorCodeValue() {
      return errorCode_;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionList.ErrorCode error_code = 1;</code>
     * @param value The enum numeric value on the wire for errorCode to set.
     * @return This builder for chaining.
     */
    public Builder setErrorCodeValue(int value) {
      
      errorCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionList.ErrorCode error_code = 1;</code>
     * @return The errorCode.
     */
    @java.lang.Override
    public info.malenkov.aspiabot.proto.SessionList.ErrorCode getErrorCode() {
      @SuppressWarnings("deprecation")
      info.malenkov.aspiabot.proto.SessionList.ErrorCode result = info.malenkov.aspiabot.proto.SessionList.ErrorCode.valueOf(errorCode_);
      return result == null ? info.malenkov.aspiabot.proto.SessionList.ErrorCode.UNRECOGNIZED : result;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionList.ErrorCode error_code = 1;</code>
     * @param value The errorCode to set.
     * @return This builder for chaining.
     */
    public Builder setErrorCode(info.malenkov.aspiabot.proto.SessionList.ErrorCode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      errorCode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.SessionList.ErrorCode error_code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorCode() {
      
      errorCode_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<info.malenkov.aspiabot.proto.Session> session_ =
      java.util.Collections.emptyList();
    private void ensureSessionIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        session_ = new java.util.ArrayList<info.malenkov.aspiabot.proto.Session>(session_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        info.malenkov.aspiabot.proto.Session, info.malenkov.aspiabot.proto.Session.Builder, info.malenkov.aspiabot.proto.SessionOrBuilder> sessionBuilder_;

    /**
     * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
     */
    public java.util.List<info.malenkov.aspiabot.proto.Session> getSessionList() {
      if (sessionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(session_);
      } else {
        return sessionBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
     */
    public int getSessionCount() {
      if (sessionBuilder_ == null) {
        return session_.size();
      } else {
        return sessionBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
     */
    public info.malenkov.aspiabot.proto.Session getSession(int index) {
      if (sessionBuilder_ == null) {
        return session_.get(index);
      } else {
        return sessionBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
     */
    public Builder setSession(
        int index, info.malenkov.aspiabot.proto.Session value) {
      if (sessionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSessionIsMutable();
        session_.set(index, value);
        onChanged();
      } else {
        sessionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
     */
    public Builder setSession(
        int index, info.malenkov.aspiabot.proto.Session.Builder builderForValue) {
      if (sessionBuilder_ == null) {
        ensureSessionIsMutable();
        session_.set(index, builderForValue.build());
        onChanged();
      } else {
        sessionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
     */
    public Builder addSession(info.malenkov.aspiabot.proto.Session value) {
      if (sessionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSessionIsMutable();
        session_.add(value);
        onChanged();
      } else {
        sessionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
     */
    public Builder addSession(
        int index, info.malenkov.aspiabot.proto.Session value) {
      if (sessionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSessionIsMutable();
        session_.add(index, value);
        onChanged();
      } else {
        sessionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
     */
    public Builder addSession(
        info.malenkov.aspiabot.proto.Session.Builder builderForValue) {
      if (sessionBuilder_ == null) {
        ensureSessionIsMutable();
        session_.add(builderForValue.build());
        onChanged();
      } else {
        sessionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
     */
    public Builder addSession(
        int index, info.malenkov.aspiabot.proto.Session.Builder builderForValue) {
      if (sessionBuilder_ == null) {
        ensureSessionIsMutable();
        session_.add(index, builderForValue.build());
        onChanged();
      } else {
        sessionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
     */
    public Builder addAllSession(
        java.lang.Iterable<? extends info.malenkov.aspiabot.proto.Session> values) {
      if (sessionBuilder_ == null) {
        ensureSessionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, session_);
        onChanged();
      } else {
        sessionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
     */
    public Builder clearSession() {
      if (sessionBuilder_ == null) {
        session_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        sessionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
     */
    public Builder removeSession(int index) {
      if (sessionBuilder_ == null) {
        ensureSessionIsMutable();
        session_.remove(index);
        onChanged();
      } else {
        sessionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
     */
    public info.malenkov.aspiabot.proto.Session.Builder getSessionBuilder(
        int index) {
      return getSessionFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
     */
    public info.malenkov.aspiabot.proto.SessionOrBuilder getSessionOrBuilder(
        int index) {
      if (sessionBuilder_ == null) {
        return session_.get(index);  } else {
        return sessionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
     */
    public java.util.List<? extends info.malenkov.aspiabot.proto.SessionOrBuilder> 
         getSessionOrBuilderList() {
      if (sessionBuilder_ != null) {
        return sessionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(session_);
      }
    }
    /**
     * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
     */
    public info.malenkov.aspiabot.proto.Session.Builder addSessionBuilder() {
      return getSessionFieldBuilder().addBuilder(
          info.malenkov.aspiabot.proto.Session.getDefaultInstance());
    }
    /**
     * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
     */
    public info.malenkov.aspiabot.proto.Session.Builder addSessionBuilder(
        int index) {
      return getSessionFieldBuilder().addBuilder(
          index, info.malenkov.aspiabot.proto.Session.getDefaultInstance());
    }
    /**
     * <code>repeated .info.malenkov.aspiabot.proto.Session session = 2;</code>
     */
    public java.util.List<info.malenkov.aspiabot.proto.Session.Builder> 
         getSessionBuilderList() {
      return getSessionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        info.malenkov.aspiabot.proto.Session, info.malenkov.aspiabot.proto.Session.Builder, info.malenkov.aspiabot.proto.SessionOrBuilder> 
        getSessionFieldBuilder() {
      if (sessionBuilder_ == null) {
        sessionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            info.malenkov.aspiabot.proto.Session, info.malenkov.aspiabot.proto.Session.Builder, info.malenkov.aspiabot.proto.SessionOrBuilder>(
                session_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        session_ = null;
      }
      return sessionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:info.malenkov.aspiabot.proto.SessionList)
  }

  // @@protoc_insertion_point(class_scope:info.malenkov.aspiabot.proto.SessionList)
  private static final info.malenkov.aspiabot.proto.SessionList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new info.malenkov.aspiabot.proto.SessionList();
  }

  public static info.malenkov.aspiabot.proto.SessionList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SessionList>
      PARSER = new com.google.protobuf.AbstractParser<SessionList>() {
    @java.lang.Override
    public SessionList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SessionList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SessionList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SessionList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public info.malenkov.aspiabot.proto.SessionList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

