// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.key.exchange.proto

package info.malenkov.aspiabot.proto;

/**
 * <pre>
 * Client to server.
 * </pre>
 *
 * Protobuf type {@code info.malenkov.aspiabot.proto.SessionResponse}
 */
public final class SessionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:info.malenkov.aspiabot.proto.SessionResponse)
    SessionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SessionResponse.newBuilder() to construct.
  private SessionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SessionResponse() {
    osName_ = "";
    computerName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SessionResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SessionResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            info.malenkov.aspiabot.proto.Version.Builder subBuilder = null;
            if (version_ != null) {
              subBuilder = version_.toBuilder();
            }
            version_ = input.readMessage(info.malenkov.aspiabot.proto.Version.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(version_);
              version_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            sessionType_ = input.readUInt32();
            break;
          }
          case 24: {

            cpuCores_ = input.readUInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            osName_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            computerName_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return info.malenkov.aspiabot.proto.AspiaKeyExchange.internal_static_info_malenkov_aspiabot_proto_SessionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return info.malenkov.aspiabot.proto.AspiaKeyExchange.internal_static_info_malenkov_aspiabot_proto_SessionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            info.malenkov.aspiabot.proto.SessionResponse.class, info.malenkov.aspiabot.proto.SessionResponse.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private info.malenkov.aspiabot.proto.Version version_;
  /**
   * <code>.info.malenkov.aspiabot.proto.Version version = 1;</code>
   * @return Whether the version field is set.
   */
  @java.lang.Override
  public boolean hasVersion() {
    return version_ != null;
  }
  /**
   * <code>.info.malenkov.aspiabot.proto.Version version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public info.malenkov.aspiabot.proto.Version getVersion() {
    return version_ == null ? info.malenkov.aspiabot.proto.Version.getDefaultInstance() : version_;
  }
  /**
   * <code>.info.malenkov.aspiabot.proto.Version version = 1;</code>
   */
  @java.lang.Override
  public info.malenkov.aspiabot.proto.VersionOrBuilder getVersionOrBuilder() {
    return getVersion();
  }

  public static final int SESSION_TYPE_FIELD_NUMBER = 2;
  private int sessionType_;
  /**
   * <code>uint32 session_type = 2;</code>
   * @return The sessionType.
   */
  @java.lang.Override
  public int getSessionType() {
    return sessionType_;
  }

  public static final int CPU_CORES_FIELD_NUMBER = 3;
  private int cpuCores_;
  /**
   * <code>uint32 cpu_cores = 3;</code>
   * @return The cpuCores.
   */
  @java.lang.Override
  public int getCpuCores() {
    return cpuCores_;
  }

  public static final int OS_NAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object osName_;
  /**
   * <code>string os_name = 4;</code>
   * @return The osName.
   */
  @java.lang.Override
  public java.lang.String getOsName() {
    java.lang.Object ref = osName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      osName_ = s;
      return s;
    }
  }
  /**
   * <code>string os_name = 4;</code>
   * @return The bytes for osName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOsNameBytes() {
    java.lang.Object ref = osName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      osName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPUTER_NAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object computerName_;
  /**
   * <code>string computer_name = 5;</code>
   * @return The computerName.
   */
  @java.lang.Override
  public java.lang.String getComputerName() {
    java.lang.Object ref = computerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      computerName_ = s;
      return s;
    }
  }
  /**
   * <code>string computer_name = 5;</code>
   * @return The bytes for computerName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getComputerNameBytes() {
    java.lang.Object ref = computerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      computerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != null) {
      output.writeMessage(1, getVersion());
    }
    if (sessionType_ != 0) {
      output.writeUInt32(2, sessionType_);
    }
    if (cpuCores_ != 0) {
      output.writeUInt32(3, cpuCores_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(osName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, osName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(computerName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, computerName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getVersion());
    }
    if (sessionType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, sessionType_);
    }
    if (cpuCores_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, cpuCores_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(osName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, osName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(computerName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, computerName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof info.malenkov.aspiabot.proto.SessionResponse)) {
      return super.equals(obj);
    }
    info.malenkov.aspiabot.proto.SessionResponse other = (info.malenkov.aspiabot.proto.SessionResponse) obj;

    if (hasVersion() != other.hasVersion()) return false;
    if (hasVersion()) {
      if (!getVersion()
          .equals(other.getVersion())) return false;
    }
    if (getSessionType()
        != other.getSessionType()) return false;
    if (getCpuCores()
        != other.getCpuCores()) return false;
    if (!getOsName()
        .equals(other.getOsName())) return false;
    if (!getComputerName()
        .equals(other.getComputerName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasVersion()) {
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
    }
    hash = (37 * hash) + SESSION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getSessionType();
    hash = (37 * hash) + CPU_CORES_FIELD_NUMBER;
    hash = (53 * hash) + getCpuCores();
    hash = (37 * hash) + OS_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getOsName().hashCode();
    hash = (37 * hash) + COMPUTER_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getComputerName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static info.malenkov.aspiabot.proto.SessionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabot.proto.SessionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.SessionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabot.proto.SessionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.SessionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabot.proto.SessionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.SessionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabot.proto.SessionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.SessionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabot.proto.SessionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.SessionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabot.proto.SessionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(info.malenkov.aspiabot.proto.SessionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Client to server.
   * </pre>
   *
   * Protobuf type {@code info.malenkov.aspiabot.proto.SessionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:info.malenkov.aspiabot.proto.SessionResponse)
      info.malenkov.aspiabot.proto.SessionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.malenkov.aspiabot.proto.AspiaKeyExchange.internal_static_info_malenkov_aspiabot_proto_SessionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.malenkov.aspiabot.proto.AspiaKeyExchange.internal_static_info_malenkov_aspiabot_proto_SessionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.malenkov.aspiabot.proto.SessionResponse.class, info.malenkov.aspiabot.proto.SessionResponse.Builder.class);
    }

    // Construct using info.malenkov.aspiabot.proto.SessionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (versionBuilder_ == null) {
        version_ = null;
      } else {
        version_ = null;
        versionBuilder_ = null;
      }
      sessionType_ = 0;

      cpuCores_ = 0;

      osName_ = "";

      computerName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return info.malenkov.aspiabot.proto.AspiaKeyExchange.internal_static_info_malenkov_aspiabot_proto_SessionResponse_descriptor;
    }

    @java.lang.Override
    public info.malenkov.aspiabot.proto.SessionResponse getDefaultInstanceForType() {
      return info.malenkov.aspiabot.proto.SessionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public info.malenkov.aspiabot.proto.SessionResponse build() {
      info.malenkov.aspiabot.proto.SessionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public info.malenkov.aspiabot.proto.SessionResponse buildPartial() {
      info.malenkov.aspiabot.proto.SessionResponse result = new info.malenkov.aspiabot.proto.SessionResponse(this);
      if (versionBuilder_ == null) {
        result.version_ = version_;
      } else {
        result.version_ = versionBuilder_.build();
      }
      result.sessionType_ = sessionType_;
      result.cpuCores_ = cpuCores_;
      result.osName_ = osName_;
      result.computerName_ = computerName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof info.malenkov.aspiabot.proto.SessionResponse) {
        return mergeFrom((info.malenkov.aspiabot.proto.SessionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(info.malenkov.aspiabot.proto.SessionResponse other) {
      if (other == info.malenkov.aspiabot.proto.SessionResponse.getDefaultInstance()) return this;
      if (other.hasVersion()) {
        mergeVersion(other.getVersion());
      }
      if (other.getSessionType() != 0) {
        setSessionType(other.getSessionType());
      }
      if (other.getCpuCores() != 0) {
        setCpuCores(other.getCpuCores());
      }
      if (!other.getOsName().isEmpty()) {
        osName_ = other.osName_;
        onChanged();
      }
      if (!other.getComputerName().isEmpty()) {
        computerName_ = other.computerName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      info.malenkov.aspiabot.proto.SessionResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (info.malenkov.aspiabot.proto.SessionResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private info.malenkov.aspiabot.proto.Version version_;
    private com.google.protobuf.SingleFieldBuilderV3<
        info.malenkov.aspiabot.proto.Version, info.malenkov.aspiabot.proto.Version.Builder, info.malenkov.aspiabot.proto.VersionOrBuilder> versionBuilder_;
    /**
     * <code>.info.malenkov.aspiabot.proto.Version version = 1;</code>
     * @return Whether the version field is set.
     */
    public boolean hasVersion() {
      return versionBuilder_ != null || version_ != null;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.Version version = 1;</code>
     * @return The version.
     */
    public info.malenkov.aspiabot.proto.Version getVersion() {
      if (versionBuilder_ == null) {
        return version_ == null ? info.malenkov.aspiabot.proto.Version.getDefaultInstance() : version_;
      } else {
        return versionBuilder_.getMessage();
      }
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.Version version = 1;</code>
     */
    public Builder setVersion(info.malenkov.aspiabot.proto.Version value) {
      if (versionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        version_ = value;
        onChanged();
      } else {
        versionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.Version version = 1;</code>
     */
    public Builder setVersion(
        info.malenkov.aspiabot.proto.Version.Builder builderForValue) {
      if (versionBuilder_ == null) {
        version_ = builderForValue.build();
        onChanged();
      } else {
        versionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.Version version = 1;</code>
     */
    public Builder mergeVersion(info.malenkov.aspiabot.proto.Version value) {
      if (versionBuilder_ == null) {
        if (version_ != null) {
          version_ =
            info.malenkov.aspiabot.proto.Version.newBuilder(version_).mergeFrom(value).buildPartial();
        } else {
          version_ = value;
        }
        onChanged();
      } else {
        versionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.Version version = 1;</code>
     */
    public Builder clearVersion() {
      if (versionBuilder_ == null) {
        version_ = null;
        onChanged();
      } else {
        version_ = null;
        versionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.Version version = 1;</code>
     */
    public info.malenkov.aspiabot.proto.Version.Builder getVersionBuilder() {
      
      onChanged();
      return getVersionFieldBuilder().getBuilder();
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.Version version = 1;</code>
     */
    public info.malenkov.aspiabot.proto.VersionOrBuilder getVersionOrBuilder() {
      if (versionBuilder_ != null) {
        return versionBuilder_.getMessageOrBuilder();
      } else {
        return version_ == null ?
            info.malenkov.aspiabot.proto.Version.getDefaultInstance() : version_;
      }
    }
    /**
     * <code>.info.malenkov.aspiabot.proto.Version version = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        info.malenkov.aspiabot.proto.Version, info.malenkov.aspiabot.proto.Version.Builder, info.malenkov.aspiabot.proto.VersionOrBuilder> 
        getVersionFieldBuilder() {
      if (versionBuilder_ == null) {
        versionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            info.malenkov.aspiabot.proto.Version, info.malenkov.aspiabot.proto.Version.Builder, info.malenkov.aspiabot.proto.VersionOrBuilder>(
                getVersion(),
                getParentForChildren(),
                isClean());
        version_ = null;
      }
      return versionBuilder_;
    }

    private int sessionType_ ;
    /**
     * <code>uint32 session_type = 2;</code>
     * @return The sessionType.
     */
    @java.lang.Override
    public int getSessionType() {
      return sessionType_;
    }
    /**
     * <code>uint32 session_type = 2;</code>
     * @param value The sessionType to set.
     * @return This builder for chaining.
     */
    public Builder setSessionType(int value) {
      
      sessionType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 session_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionType() {
      
      sessionType_ = 0;
      onChanged();
      return this;
    }

    private int cpuCores_ ;
    /**
     * <code>uint32 cpu_cores = 3;</code>
     * @return The cpuCores.
     */
    @java.lang.Override
    public int getCpuCores() {
      return cpuCores_;
    }
    /**
     * <code>uint32 cpu_cores = 3;</code>
     * @param value The cpuCores to set.
     * @return This builder for chaining.
     */
    public Builder setCpuCores(int value) {
      
      cpuCores_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 cpu_cores = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCpuCores() {
      
      cpuCores_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object osName_ = "";
    /**
     * <code>string os_name = 4;</code>
     * @return The osName.
     */
    public java.lang.String getOsName() {
      java.lang.Object ref = osName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        osName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string os_name = 4;</code>
     * @return The bytes for osName.
     */
    public com.google.protobuf.ByteString
        getOsNameBytes() {
      java.lang.Object ref = osName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        osName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string os_name = 4;</code>
     * @param value The osName to set.
     * @return This builder for chaining.
     */
    public Builder setOsName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      osName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string os_name = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOsName() {
      
      osName_ = getDefaultInstance().getOsName();
      onChanged();
      return this;
    }
    /**
     * <code>string os_name = 4;</code>
     * @param value The bytes for osName to set.
     * @return This builder for chaining.
     */
    public Builder setOsNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      osName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object computerName_ = "";
    /**
     * <code>string computer_name = 5;</code>
     * @return The computerName.
     */
    public java.lang.String getComputerName() {
      java.lang.Object ref = computerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        computerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string computer_name = 5;</code>
     * @return The bytes for computerName.
     */
    public com.google.protobuf.ByteString
        getComputerNameBytes() {
      java.lang.Object ref = computerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        computerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string computer_name = 5;</code>
     * @param value The computerName to set.
     * @return This builder for chaining.
     */
    public Builder setComputerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      computerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string computer_name = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearComputerName() {
      
      computerName_ = getDefaultInstance().getComputerName();
      onChanged();
      return this;
    }
    /**
     * <code>string computer_name = 5;</code>
     * @param value The bytes for computerName to set.
     * @return This builder for chaining.
     */
    public Builder setComputerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      computerName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:info.malenkov.aspiabot.proto.SessionResponse)
  }

  // @@protoc_insertion_point(class_scope:info.malenkov.aspiabot.proto.SessionResponse)
  private static final info.malenkov.aspiabot.proto.SessionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new info.malenkov.aspiabot.proto.SessionResponse();
  }

  public static info.malenkov.aspiabot.proto.SessionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SessionResponse>
      PARSER = new com.google.protobuf.AbstractParser<SessionResponse>() {
    @java.lang.Override
    public SessionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SessionResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SessionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SessionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public info.malenkov.aspiabot.proto.SessionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

