// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.router.admin.proto

package info.malenkov.aspiabot.proto;

public interface UserListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info.malenkov.aspiabot.proto.UserList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.info.malenkov.aspiabot.proto.UserList.ErrorCode error_code = 1;</code>
   * @return The enum numeric value on the wire for errorCode.
   */
  int getErrorCodeValue();
  /**
   * <code>.info.malenkov.aspiabot.proto.UserList.ErrorCode error_code = 1;</code>
   * @return The errorCode.
   */
  info.malenkov.aspiabot.proto.UserList.ErrorCode getErrorCode();

  /**
   * <code>repeated .info.malenkov.aspiabot.proto.User user = 2;</code>
   */
  java.util.List<info.malenkov.aspiabot.proto.User> 
      getUserList();
  /**
   * <code>repeated .info.malenkov.aspiabot.proto.User user = 2;</code>
   */
  info.malenkov.aspiabot.proto.User getUser(int index);
  /**
   * <code>repeated .info.malenkov.aspiabot.proto.User user = 2;</code>
   */
  int getUserCount();
  /**
   * <code>repeated .info.malenkov.aspiabot.proto.User user = 2;</code>
   */
  java.util.List<? extends info.malenkov.aspiabot.proto.UserOrBuilder> 
      getUserOrBuilderList();
  /**
   * <code>repeated .info.malenkov.aspiabot.proto.User user = 2;</code>
   */
  info.malenkov.aspiabot.proto.UserOrBuilder getUserOrBuilder(
      int index);
}
