// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.router.admin.proto

package info.malenkov.aspiabot.proto;

/**
 * Protobuf enum {@code info.malenkov.aspiabot.proto.UserRequestType}
 */
public enum UserRequestType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>USER_REQUEST_UNKNOWN = 0;</code>
   */
  USER_REQUEST_UNKNOWN(0),
  /**
   * <code>USER_REQUEST_ADD = 1;</code>
   */
  USER_REQUEST_ADD(1),
  /**
   * <code>USER_REQUEST_MODIFY = 2;</code>
   */
  USER_REQUEST_MODIFY(2),
  /**
   * <code>USER_REQUEST_DELETE = 3;</code>
   */
  USER_REQUEST_DELETE(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>USER_REQUEST_UNKNOWN = 0;</code>
   */
  public static final int USER_REQUEST_UNKNOWN_VALUE = 0;
  /**
   * <code>USER_REQUEST_ADD = 1;</code>
   */
  public static final int USER_REQUEST_ADD_VALUE = 1;
  /**
   * <code>USER_REQUEST_MODIFY = 2;</code>
   */
  public static final int USER_REQUEST_MODIFY_VALUE = 2;
  /**
   * <code>USER_REQUEST_DELETE = 3;</code>
   */
  public static final int USER_REQUEST_DELETE_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static UserRequestType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static UserRequestType forNumber(int value) {
    switch (value) {
      case 0: return USER_REQUEST_UNKNOWN;
      case 1: return USER_REQUEST_ADD;
      case 2: return USER_REQUEST_MODIFY;
      case 3: return USER_REQUEST_DELETE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<UserRequestType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      UserRequestType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<UserRequestType>() {
          public UserRequestType findValueByNumber(int number) {
            return UserRequestType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return info.malenkov.aspiabot.proto.AspiaRouterAdmin.getDescriptor().getEnumTypes().get(1);
  }

  private static final UserRequestType[] VALUES = values();

  public static UserRequestType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private UserRequestType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:info.malenkov.aspiabot.proto.UserRequestType)
}

