// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspia.common.proto

package info.malenkov.aspiabot.proto;

/**
 * Protobuf type {@code info.malenkov.aspiabot.proto.Version}
 */
public final class Version extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:info.malenkov.aspiabot.proto.Version)
    VersionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Version.newBuilder() to construct.
  private Version(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Version() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Version();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Version(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            major_ = input.readUInt32();
            break;
          }
          case 16: {

            minor_ = input.readUInt32();
            break;
          }
          case 24: {

            patch_ = input.readUInt32();
            break;
          }
          case 32: {

            revision_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return info.malenkov.aspiabot.proto.AspiaCommon.internal_static_info_malenkov_aspiabot_proto_Version_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return info.malenkov.aspiabot.proto.AspiaCommon.internal_static_info_malenkov_aspiabot_proto_Version_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            info.malenkov.aspiabot.proto.Version.class, info.malenkov.aspiabot.proto.Version.Builder.class);
  }

  public static final int MAJOR_FIELD_NUMBER = 1;
  private int major_;
  /**
   * <code>uint32 major = 1;</code>
   * @return The major.
   */
  @java.lang.Override
  public int getMajor() {
    return major_;
  }

  public static final int MINOR_FIELD_NUMBER = 2;
  private int minor_;
  /**
   * <code>uint32 minor = 2;</code>
   * @return The minor.
   */
  @java.lang.Override
  public int getMinor() {
    return minor_;
  }

  public static final int PATCH_FIELD_NUMBER = 3;
  private int patch_;
  /**
   * <code>uint32 patch = 3;</code>
   * @return The patch.
   */
  @java.lang.Override
  public int getPatch() {
    return patch_;
  }

  public static final int REVISION_FIELD_NUMBER = 4;
  private int revision_;
  /**
   * <code>uint32 revision = 4;</code>
   * @return The revision.
   */
  @java.lang.Override
  public int getRevision() {
    return revision_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (major_ != 0) {
      output.writeUInt32(1, major_);
    }
    if (minor_ != 0) {
      output.writeUInt32(2, minor_);
    }
    if (patch_ != 0) {
      output.writeUInt32(3, patch_);
    }
    if (revision_ != 0) {
      output.writeUInt32(4, revision_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (major_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, major_);
    }
    if (minor_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, minor_);
    }
    if (patch_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, patch_);
    }
    if (revision_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, revision_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof info.malenkov.aspiabot.proto.Version)) {
      return super.equals(obj);
    }
    info.malenkov.aspiabot.proto.Version other = (info.malenkov.aspiabot.proto.Version) obj;

    if (getMajor()
        != other.getMajor()) return false;
    if (getMinor()
        != other.getMinor()) return false;
    if (getPatch()
        != other.getPatch()) return false;
    if (getRevision()
        != other.getRevision()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MAJOR_FIELD_NUMBER;
    hash = (53 * hash) + getMajor();
    hash = (37 * hash) + MINOR_FIELD_NUMBER;
    hash = (53 * hash) + getMinor();
    hash = (37 * hash) + PATCH_FIELD_NUMBER;
    hash = (53 * hash) + getPatch();
    hash = (37 * hash) + REVISION_FIELD_NUMBER;
    hash = (53 * hash) + getRevision();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static info.malenkov.aspiabot.proto.Version parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabot.proto.Version parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.Version parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabot.proto.Version parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.Version parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.malenkov.aspiabot.proto.Version parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.Version parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabot.proto.Version parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.Version parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabot.proto.Version parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.malenkov.aspiabot.proto.Version parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.malenkov.aspiabot.proto.Version parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(info.malenkov.aspiabot.proto.Version prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code info.malenkov.aspiabot.proto.Version}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:info.malenkov.aspiabot.proto.Version)
      info.malenkov.aspiabot.proto.VersionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.malenkov.aspiabot.proto.AspiaCommon.internal_static_info_malenkov_aspiabot_proto_Version_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.malenkov.aspiabot.proto.AspiaCommon.internal_static_info_malenkov_aspiabot_proto_Version_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.malenkov.aspiabot.proto.Version.class, info.malenkov.aspiabot.proto.Version.Builder.class);
    }

    // Construct using info.malenkov.aspiabot.proto.Version.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      major_ = 0;

      minor_ = 0;

      patch_ = 0;

      revision_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return info.malenkov.aspiabot.proto.AspiaCommon.internal_static_info_malenkov_aspiabot_proto_Version_descriptor;
    }

    @java.lang.Override
    public info.malenkov.aspiabot.proto.Version getDefaultInstanceForType() {
      return info.malenkov.aspiabot.proto.Version.getDefaultInstance();
    }

    @java.lang.Override
    public info.malenkov.aspiabot.proto.Version build() {
      info.malenkov.aspiabot.proto.Version result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public info.malenkov.aspiabot.proto.Version buildPartial() {
      info.malenkov.aspiabot.proto.Version result = new info.malenkov.aspiabot.proto.Version(this);
      result.major_ = major_;
      result.minor_ = minor_;
      result.patch_ = patch_;
      result.revision_ = revision_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof info.malenkov.aspiabot.proto.Version) {
        return mergeFrom((info.malenkov.aspiabot.proto.Version)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(info.malenkov.aspiabot.proto.Version other) {
      if (other == info.malenkov.aspiabot.proto.Version.getDefaultInstance()) return this;
      if (other.getMajor() != 0) {
        setMajor(other.getMajor());
      }
      if (other.getMinor() != 0) {
        setMinor(other.getMinor());
      }
      if (other.getPatch() != 0) {
        setPatch(other.getPatch());
      }
      if (other.getRevision() != 0) {
        setRevision(other.getRevision());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      info.malenkov.aspiabot.proto.Version parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (info.malenkov.aspiabot.proto.Version) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int major_ ;
    /**
     * <code>uint32 major = 1;</code>
     * @return The major.
     */
    @java.lang.Override
    public int getMajor() {
      return major_;
    }
    /**
     * <code>uint32 major = 1;</code>
     * @param value The major to set.
     * @return This builder for chaining.
     */
    public Builder setMajor(int value) {
      
      major_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 major = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMajor() {
      
      major_ = 0;
      onChanged();
      return this;
    }

    private int minor_ ;
    /**
     * <code>uint32 minor = 2;</code>
     * @return The minor.
     */
    @java.lang.Override
    public int getMinor() {
      return minor_;
    }
    /**
     * <code>uint32 minor = 2;</code>
     * @param value The minor to set.
     * @return This builder for chaining.
     */
    public Builder setMinor(int value) {
      
      minor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 minor = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinor() {
      
      minor_ = 0;
      onChanged();
      return this;
    }

    private int patch_ ;
    /**
     * <code>uint32 patch = 3;</code>
     * @return The patch.
     */
    @java.lang.Override
    public int getPatch() {
      return patch_;
    }
    /**
     * <code>uint32 patch = 3;</code>
     * @param value The patch to set.
     * @return This builder for chaining.
     */
    public Builder setPatch(int value) {
      
      patch_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 patch = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPatch() {
      
      patch_ = 0;
      onChanged();
      return this;
    }

    private int revision_ ;
    /**
     * <code>uint32 revision = 4;</code>
     * @return The revision.
     */
    @java.lang.Override
    public int getRevision() {
      return revision_;
    }
    /**
     * <code>uint32 revision = 4;</code>
     * @param value The revision to set.
     * @return This builder for chaining.
     */
    public Builder setRevision(int value) {
      
      revision_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 revision = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRevision() {
      
      revision_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:info.malenkov.aspiabot.proto.Version)
  }

  // @@protoc_insertion_point(class_scope:info.malenkov.aspiabot.proto.Version)
  private static final info.malenkov.aspiabot.proto.Version DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new info.malenkov.aspiabot.proto.Version();
  }

  public static info.malenkov.aspiabot.proto.Version getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Version>
      PARSER = new com.google.protobuf.AbstractParser<Version>() {
    @java.lang.Override
    public Version parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Version(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Version> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Version> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public info.malenkov.aspiabot.proto.Version getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

